DROP TABLE Contient;
DROP TABLE liste_jouet ;
DROP TABLE commander ;
DROP TABLE Passe_par;
DROP TABLE Fabrique ;
DROP TABLE Produit ;
DROP TABLE Participe ;
DROP TABLE Constituer_par ;
DROP TABLE Substitut;
DROP TABLE Commande ;
DROP TABLE Remplace ;
DROP TABLE Possede ;
DROP TABLE Jouet ;
DROP TABLE Enfants ;
DROP TABLE Tournee ;
DROP TABLE Renne ;
DROP TABLE Elfes ;
DROP TABLE Traineau ;
DROP TABLE Equipe ;
DROP TABLE Flotte ;
DROP TABLE Intermittent ;
DROP TABLE Entrepot ;
DROP TABLE Sous_traitant ;
DROP TABLE Matieres_premieres ;
DROP TABLE Atelier ;
DROP TABLE Specialite ;
DROP TABLE lutins ;
DROP TABLE mdp ;